language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential autoconf nasm
    - git clone https://github.com/mozilla/mozjpeg.git
    - cd mozjpeg
    - git checkout 7faa703ebf7360e5c0a37d71a74c293232998340
    - autoreconf -fiv
    - ./configure --with-jpeg8
    - make && sudo make install
    - cd ..
script:
    - make && make test && ./test.sh
